import { faCreditCard, faMoneyBill1, faStar, faPenToSquare, faTrashCan, faCircleXmark, IconDefinition } from '@fortawesome/free-regular-svg-icons';
import {
  faWallet,
  faStar as faStarSolid,
  faPlus,
  faMobileScreen as faMobile,
  faFilm,
  faUtensils,
  faCoins,
  faLandmark,
  faDollarSign,
  faPiggyBank,
  faSackDollar,
  faTrashCan as faTrashCanSolid,
  faCartShopping,
  faCartPlus,
  faCar,
  faCarSide,
  faGasPump,
  faTrain,
  faMoneyBillTransfer,
  faBusSimple,
  faGift,
  faBasketShopping,
  faBagShopping,
  faPizzaSlice,
  faMartiniGlass,
  faBeer,
  faPlane,
  faPlaneDeparture,
  faPlaneUp,
  faEarthAmericas,
  faSun,
  faBicycle,
  faClose,
  faArrowRight,
  faArrowUp,
  faArrowDown,
  faArrowLeft,
  faArrowsLeftRight,
  faArrowsUpDown,
  faArrowRightArrowLeft,
  faChevronUp,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faReceipt,
  faCreditCard as faCreditCardSolid,
  faChartPie,
  faIcons as faCategories,
  faCalendarDays,
  faEllipsis,
} from '@fortawesome/free-solid-svg-icons';

export interface IconsInterface {
  [index: string]: { [index: string]: IconDefinition };
}

export const faIcons: IconsInterface = {
  accounts: {
    faCreditCard,
    faMoneyBill1,
    faWallet,
    faCoins,
    faLandmark,
    faDollarSign,
    faPiggyBank,
    faSackDollar,
  },
  categories: {
    faMoneyBill1,
    faMobile,
    faFilm,
    faUtensils,
    faCartShopping,
    faCartPlus,
    faCar,
    faCarSide,
    faGasPump,
    faTrain,
    faBusSimple,
    faGift,
    faBasketShopping,
    faBagShopping,
    faPizzaSlice,
    faMartiniGlass,
    faBeer,
    faPlane,
    faPlaneDeparture,
    faPlaneUp,
    faEarthAmericas,
    faSun,
    faBicycle,
    faCircleXmark,
    faMoneyBillTransfer,
    faCoins,
    faEllipsis,
  },
  type: {
    faArrowLeft,
    faArrowRight,
    faArrowRightArrowLeft,
  },
  others: {
    faStarSolid,
    faStar,
    faTrashCan,
    faPenToSquare,
    faPlus,
    faTrashCanSolid,
    faMoneyBillTransfer,
    faClose,
    faArrowRight,
    faArrowUp,
    faArrowDown,
    faArrowLeft,
    faArrowsLeftRight,
    faArrowsUpDown,
    faArrowRightArrowLeft,
    faChevronUp,
    faChevronDown,
    faChevronLeft,
    faChevronRight,
    faReceipt,
    faCreditCardSolid,
    faChartPie,
    faCategories,
    faCalendarDays,
  },
};
